In [ ]:
# Shape: samples x channels x width x height

In [16]:
t = torch.tensor([[
                   [[1, 2, 3],
                    [3, 4, 3]],
                   [[5, 6, 3],
                    [7, 8, 3]],
                   [[5, 6, 3],
                    [7, 8, 3]]],
                  [[[1, 2, 3],
                    [3, 4, 3]],
                   [[5, 6, 3],
                    [7, 8, 3]],
                   [[5, 6, 3],
                    [7, 8, 3]]
                   ]])
print(t.shape)
print(t)

torch.Size([2, 3, 2, 3])
tensor([[[[1, 2, 3],
          [3, 4, 3]],

         [[5, 6, 3],
          [7, 8, 3]],

         [[5, 6, 3],
          [7, 8, 3]]],


        [[[1, 2, 3],
          [3, 4, 3]],

         [[5, 6, 3],
          [7, 8, 3]],

         [[5, 6, 3],
          [7, 8, 3]]]])


In [17]:
torch.flatten(t)

tensor([1, 2, 3, 3, 4, 3, 5, 6, 3, 7, 8, 3, 5, 6, 3, 7, 8, 3, 1, 2, 3, 3, 4, 3,
        5, 6, 3, 7, 8, 3, 5, 6, 3, 7, 8, 3])

In [23]:
t_ = torch.flatten(t, start_dim=2)
print(t_)
print(t_.shape)

tensor([[[1, 2, 3, 3, 4, 3],
         [5, 6, 3, 7, 8, 3],
         [5, 6, 3, 7, 8, 3]],

        [[1, 2, 3, 3, 4, 3],
         [5, 6, 3, 7, 8, 3],
         [5, 6, 3, 7, 8, 3]]])
torch.Size([2, 3, 6])
